steps:
  - name: 'gcr.io/cloud-builders/docker'
    args: [
      'build', '-t', 'eu.gcr.io/cloud-computing-continuum-2024/three-data-backend:latest','./backend/'
    ]
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'eu.gcr.io/cloud-computing-continuum-2024/three-data-backend:latest']

  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk' # Using gcloud SDK image
    entrypoint: 'gcloud'
    args: [
      'run', 'deploy', 'three-data-backend',
      '--image', 'eu.gcr.io/cloud-computing-continuum-2024/three-data-backend:latest',
      '--region', 'europe-north1',
      '--platform', 'managed',
      '--allow-unauthenticated',
      '--set-env-vars', 'INSTANCE_UNIX_SOCKET=/cloudsql/s5terraform:europe-north1:e4-sql',
      '--set-env-vars', 'INSTANCE_CONNECTION_NAME=s5terraform:europe-north1:e4-sql',
      '--set-env-vars', 'DB_NAME=e4-db',
      '--set-env-vars', 'DB_USER=e4-user',
      '--set-env-vars', 'DB_PASS=test',
      '--add-cloudsql-instances', '<YOUR_VALUE>', # Cloud SQL instance connection
      '--port', '8080'
  ]
options:
  logging: CLOUD_LOGGING_ONLY